apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xrq7i1xv9-nodejs 
  janus-idp.io/tekton: xrq7i1xv9-nodejs
  backstage.io/kubernetes-id: xrq7i1xv9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xrq7i1xv9-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  