apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xrq7i1xv9-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-f1b4b88716.1710.p3.openshiftapps.com/rhtap/rhtap-qe:09dbf21d1c6c60fc82e633a97777aaffb980d5ff@sha256:531d3e4950b5d83d49fa8461985c70c5085ac990733f38839dffb342209e855d
          name: container-image
